# Generated by Django 3.2.19 on 2024-10-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_addr', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('channel', models.IntegerField(default=0)),
            ],
        ),
    ]
