# Generated by Django 5.1.2 on 2024-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulb',
            name='channel',
            field=models.BooleanField(default=0),
        ),
    ]
