# Generated by Django 5.1.2 on 2024-10-21 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_bulb_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulb',
            name='enabled',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='bulb',
            name='channel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(511), django.core.validators.MinValueValidator(1)]),
        ),
    ]
