# Generated by Django 5.1.2 on 2024-10-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_bulb_enabled_alter_bulb_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulb',
            options={'ordering': ['ip_addr']},
        ),
    ]
